name: PRforsnykwithbash
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  SNykPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment variables
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
             echo "running script"
             chmod +x script.sh
             ./script.sh $SNYK_TOKEN
             
             
             
             
             
